name: VSCode Version Matrix
description: Retrieves VSCode's dependency versions (Electron, Node, and Chromium)
author: EcksDy
branding:
  color: blue
  icon: code

inputs:
  token:
    description: GitHub token to access GitHub's API
    required: true
  version:
    description: VSCode version to retrieve dependency versions for
    required: false
    default: latest

outputs:
  vscode-version-name:
    description: The name of the VSCode release, defaults to version if not found
  vscode-version:
    description: Same as input version, but with the latest tag resolved
  released-at:
    description: Date of the VSCode release
  electron-version:
    description: Electron version used by VSCode
  node-version:
    description: Node version used by VSCode
  chromium-version:
    description: Chromium version used by VSCode

runs:
  using: node20
  main: dist/index.js
