name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Output
        id: output
        run: |
          echo "vscode-version-name = ${{ steps.test-action.outputs.vscode-version-name }}"
          echo "vscode-version = ${{ steps.test-action.outputs.vscode-version }}"
          echo "released-at = ${{ steps.test-action.outputs.released-at }}"
          echo "electron-version = ${{ steps.test-action.outputs.electron-version }}"
          echo "node-version = ${{ steps.test-action.outputs.node-version }}"
          echo "chromium-version = ${{ steps.test-action.outputs.chromium-version }}"
